//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVCPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fund
    {
        public int FundID { get; set; }
        public int Fund1 { get; set; }
        public int AccountNumber { get; set; }
    
        public virtual BanksCustomer BanksCustomer { get; set; }
    }
}
