//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVCPractice.Common
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginDetails
    {
        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First name cannot be empty")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "First name cannot be longer than 20 characters and minimum 2 characters")]
        [RegularExpression("^([a-zA-Z]{2,})$", ErrorMessage = "First name contains only alphabets")]
        public string CustomerName { get; set; }

        [Display(Name = "Account number")]
        [Required(ErrorMessage = "Account number name cannot be empty maximun lenght is 10 digit")]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Invalid account number")]
        public int AccountNumber1 { get; set; }

        [Display(Name = "User Name")]
        [Required(ErrorMessage = "User name cannot be empty")]
        [StringLength(20, MinimumLength = 2, ErrorMessage = "User name cannot be longer than 20 characters and minimum 2 characters")]
        public string UserName1 { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password cannot be empty")]
        [StringLength(20, MinimumLength = 8, ErrorMessage = "Password cannot be longer than 20 characters and minimum 8 characters")]
        [DataType(DataType.Password, ErrorMessage = "Invalid password")]
        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=]).{8,20}$", ErrorMessage = "Password contains one special character, one uppercase, one lowercase, minimum 8 and maximum 16 characters")]
        public string Password1 { get; set; }

        public string UserRole { get; set; }

        public Nullable<int> CurrentBalance { get; set; }

        public int Fund { get; set; }

        public string TransactionPassword { get; set; }
    }
}
